version = "1.0"

[main]
name = "Pico configuration"

    [main.config]
    name = "Configuration Options"

        [main.config.site_title]
        ask = "Website title"
        type = "string"
        help = "Customise the title of your website"
        bind = "site_title:/var/www/pico/config/config.yml"
