packaging_format = 2

id = "pico"
name = "Pico"
description.en = "Stupidly simple, blazing fast, flat file CMS"
description.fr = "CMS incroyablement simple et rapide comme l'éclair"

version = "3.0.0~ynh2"

maintainers = []

[upstream]
license = "MIT"
website = "https://picocms.org/"
admindoc = "https://picocms.org/docs/"
code = "https://github.com/picocms/Pico"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso =  false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pico"

    [install.site_title]
    ask.en = "The title of your website"
    ask.fr = "Le titre de votre site web"
    type = "string"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/picocms/Pico/releases/download/v3.0.0-alpha.2/pico-release-v3.0.0-alpha.2.zip"
        sha256 = "f06dd247e68a62223b2f4300e2458990e19fd91f09f9312ad1a49e5561444997"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages ="php8.0-dom php8.0-mbstring"
